export const envConfiguration = {
  MONGODB_URI: 'MONGODB_URI',
  MONGODB_COMPASS: 'MONGODB_COMPASS',
  PORT: 'PORT',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_EXPIRES: 'JWT_EXPIRES',
  NODE_ENV: 'NODE_ENV',
};
